### ISSUE TITLE
Password-Reminder no longer functions.

### ISSUE THREAD

**Issue by TheZaphodBeeblebrox** [Primeaxiom/StellarRealms#10]
My cousin attempted to use password reminder this morning and used the offered password from: noreply@stellarrealms.com  

It was a long jumbled code, more than 20 characters.  She  took everything but the quotes and copy and pasted them 3 times, even asked for another reminder.  It took us to the "ugly" failed login page.

Fortunately, I had wrote her password down in my notes and she was able to get in.   But you might want to look into this.

**Comment by jbyron** [comment]
fixed
