### ISSUE TITLE
Error message when trying to access Diplomacy screen

### ISSUE THREAD

**Issue by GalacticMuseum** [Primeaxiom/StellarRealms#13]
http://forums.stellarrealms.com/viewtopic.php?f=10&t=580&p=3808#p3808

This , when I click on diplomacy. 

---

OOPS! Well we really didn't need that planet anyways.

I know! We made that button all shiney and red! You couldn't help yourself. Totally our fault.

The issue has been logged and reported the interstellar clean up crew.

Your reference number (if you really care) is: A0000

Err: (-2146827788) Variable is undefined: 'AID'
SrvErr: ()
Src:
Location: File: /diplomacy.asp - Line: 64 - Pos: -1
Client IP: 142.166.237.127
Referrer: http://www.stellar-realms.com/sidebar.asp

LoginSessionID: f305eac87a644fbe836264be510228aa
authUserId: 343
authPlanetId: 35
authRemoteIp: 142.166.237.127

**Comment by jbyron** [comment]
Clarification.  This happens when trying to join an alliance

**Comment by jbyron** [comment]
fixed
