### ISSUE TITLE
500 Error on Planet Overview

### ISSUE THREAD

**Issue by Vorkuta26** [Primeaxiom/StellarRealms#2]
Happens even if auto-login is OFF and the rest of the screens load.  Probably unrelated to auto-login issue.

**Comment by jbyron** [comment]
Can you provide steps to reproduce?  I just tried it myself and it is working fine.

**Comment by Vorkuta26** [comment]
You'll need to log in as me.  I suspect it's tied to my planet data.

**Comment by GalacticMuseum** [comment]
I recently created a planet. 500 Error on Planet Overview did not occur until I set a research project. After that my planet overview gives a 500 error. All other screens appear to be available.

**Comment by GalacticMuseum** [comment]
The is Freeda (don't feel like making a seperate account).  The 500 Error also appeared for me but it happened after I set my first construction, I had not set my research yet.

**Comment by TheZaphodBeeblebrox** [comment]
As previously noted by Freeds and Motown, the error occurs after either starting a Research or Construction queue first.  Doing one or the other makes the Planet Overview page error.

Upon recreating my planet, Planet Overview worked fine until something was queued up.
