### ISSUE TITLE
Diplomacy: Recall has crashed GHC page.  

### ISSUE THREAD

**Issue by TheZaphodBeeblebrox** [Primeaxiom/StellarRealms#26]
I didn't see anything wrong with proposing decrease or increase in commerce fees or genocide penalty - but when the Recall was made, I lost contact with my diplomacy page.

I'm willing to bet anyone with an embassy also lost their diplomacy page as well.

**Comment by TheZaphodBeeblebrox** [comment]
Fellow councilmembers have reported that submitting votes for the genocide penalty caused the crash after the recall, and not before as it was for me.

So the recall may not be what triggered the issue.  Though, I still suspect it is mostly exclusive to GHC members.

**Comment by jbyron** [comment]
I fixed a bug that was generating significant errors from this code earlier today.  I'm assuming that was the issue and this is now fixed.  Please reopen if necessary.
