### ISSUE TITLE
Estimated End Date is Turning Backwards.

### ISSUE THREAD

**Issue by TheZaphodBeeblebrox** [Primeaxiom/StellarRealms#28]
As of now, the Realm Rules tab on the Planet Overview shows this.

Realm Rules
Realm Number:   30 
Realm Name: Here's Johnny 
Round Type: Standard 
Game Start Year:    2700 
Game Turns: 3600 
Turns Remaining:    2223 
Start Date: 2015-11-30 00:00:00 GMT 
Estimated End Date: 2015-12-30 21:00:00 GMT 
Scored Round:   yes  
Max Fleet Size: 4000 
Nmbr of Planets:    33 
Active Planets: 27 / 19 
Current Server Time:    2015-12-19 18:22:59
Population Growth Enabled:  yes  
Commerce Enabled:   yes  
GHC Enabled:    yes  
Protection Years:   250
Crew Loss Multiplier:   100%

We're less than half-way finished with the round, yet it will end in 11 days?  Unlikely.  It's been ticking backwards for quite some time.  With this in consideration that the turns are continuing to click backwards, by my cousin's calculations, the round will prematurely end on Christmas Day!   When it should be closer to the 18th of January.

**Comment by jbyron** [comment]
should be fixed now
