### ISSUE TITLE
Broken link from Login to Main (500 error related?)

### ISSUE THREAD

**Issue by TheZaphodBeeblebrox** [Primeaxiom/StellarRealms#3]
Not related to the Auto-login bug.  

Upon logging in, with cookies disabled, the login screen will fail to link to the main page.  It will instead take you to the 500 page while still displaying.  www.stellar-realms.com/login.asp instead of www.stellar-realms.com/main.asp in the url. 

After manually typing into the url the correct link, main.asp in place of login.asp, it works fine.  Broken link perhaps?

**Comment by TheZaphodBeeblebrox** [comment]
www.stellar-realms.com/login.asp now reads as an error.
www.stellar-realms.com/default.asp is the new login page

However, upon logging in on default.asp, you are taken to: a rather humorous page at login.asp.   That displays the following:

OOPS! Well we really didn't need that planet anyways.

I know! We made that button all shiney and red! You couldn't help yourself. Totally our fault.

The issue has been logged and reported the interstellar clean up crew.

Your reference number (if you really care) is: A0000

Err: (-2147220960) The "SendUsing" configuration value is invalid. 
SrvErr: () 
Src: 
Location: File: /login.asp - Line: 142 - Pos: -1
Client IP: 71.238.235.72
Referrer: http://www.stellar-realms.com/default.asp
Return to Stellar Realms

Love it!  But you still have to manually type in the url bar: 

 www.stellar-realms.com/main.asp

**Comment by jbyron** [comment]
Want to try again pls?  I made a tweak.  I haven't been able to reproduce it on my side at all so I can't confirm if it's still happening or not.

**Comment by TheZaphodBeeblebrox** [comment]
I believe this is working as it should now.  Awesome.

**Comment by jbyron** [comment]
As per TheZaphodBeeblebrox comment, i am closing the issue.
