### ISSUE TITLE
SERIOUS BUG: Recall/Deployment screen no longer available

### ISSUE THREAD

**Issue by TheZaphodBeeblebrox** [Primeaxiom/StellarRealms#35]
After the re-implementation of commerce maintenance fees,  outbound ships that return home cause the fleet recall/deployment option to become no longer available.  This all players can no longer conduct bomb, recon, or explore planets.  This also leaves players vulnerable to attacks, but a simple solution is to place fleets into commerce and pay the maintenance fee.

This is a serious error, more serious than others as it makes the game virtually unplayable.  I'm sorry Zippit and Vorkuta, but we must call upon your expert coding abilities again.

**Comment by jbyron** [comment]
Fixed
