### ISSUE TITLE
Commerce: Restricted Sales (Broken Link)

### ISSUE THREAD

**Issue by TheZaphodBeeblebrox** [Primeaxiom/StellarRealms#6]
Going to commerce and visiting restricted sales brings up an error page.  Valid information posted:

Err: (-2146828275) Type mismatch: 'checkLoginSession'
SrvErr: () 
Src: 
Location: File: /include/authenticate.asp - Line: 11 - Pos: -1

**Comment by jbyron** [comment]
fixed
